main.o: main.F90 _mod_shift _mod_geoopt _mod_mainio _mod_charmanip _mod_initprogram _mod_scc _mod_flib_wxml _mod_nonscc _mod_lapackroutines _mod_orbitalequiv _mod_populations allocate.h _mod_numderivs2 _mod_energies _mod_elecconstraints _mod_angmomentum _mod_externalcharges _mod_potentials _mod_formatout _mod_spin _mod_eigenvects _mod_sparse2dense _mod_blasroutines _mod_parser _mod_stress _mod_taggedoutput _mod_densitymatrix _mod_simplealgebra _mod_mdcommon _mod_fileid _mod_inputdata_ _mod_constants _mod_etemp _mod_repulsive _mod_spinorbit _mod_hsdutils _mod_mixer _mod_forces _mod_dftbplsu
main.o = main.o $(_mod_shift) $(_mod_geoopt) $(_mod_mainio) $(_mod_charmanip) $(_mod_initprogram) $(_mod_scc) $(_mod_flib_wxml) $(_mod_nonscc) $(_mod_lapackroutines) $(_mod_orbitalequiv) $(_mod_populations) $(allocate.h) $(_mod_numderivs2) $(_mod_energies) $(_mod_elecconstraints) $(_mod_angmomentum) $(_mod_externalcharges) $(_mod_potentials) $(_mod_formatout) $(_mod_spin) $(_mod_eigenvects) $(_mod_sparse2dense) $(_mod_blasroutines) $(_mod_parser) $(_mod_stress) $(_mod_taggedoutput) $(_mod_densitymatrix) $(_mod_simplealgebra) $(_mod_mdcommon) $(_mod_fileid) $(_mod_inputdata_) $(_mod_constants) $(_mod_etemp) $(_mod_repulsive) $(_mod_spinorbit) $(_mod_hsdutils) $(_mod_mixer) $(_mod_forces) $(_mod_dftbplsu)
_mod_main: main.o
_mod_main = $(main.o)

main_ctypes.o: main_ctypes.F90 _mod_main
main_ctypes.o = main_ctypes.o $(_mod_main)

dftb+.o: dftb+.F90 _mod_main
dftb+.o = dftb+.o $(_mod_main)

eigenvects.o: eigenvects.F90 _mod_sparse2dense _mod_commontypes allocate.h _mod_message _mod_angmomentum _mod_eigensolver _mod_accuracy assert.h
eigenvects.o = eigenvects.o $(_mod_sparse2dense) $(_mod_commontypes) $(allocate.h) $(_mod_message) $(_mod_angmomentum) $(_mod_eigensolver) $(_mod_accuracy) $(assert.h)
_mod_eigenvects: eigenvects.o
_mod_eigenvects = $(eigenvects.o)

energies.o: energies.F90 _mod_accuracy assert.h allocate.h
energies.o = energies.o $(_mod_accuracy) $(assert.h) $(allocate.h)
_mod_energies: energies.o
_mod_energies = $(energies.o)

initprogram.o: initprogram.F90 _mod_geoopt _mod_dispuff _mod_diismixer _mod_scc _mod_dummythermostat assert.h _mod_slakocont _mod_orbitalequiv _mod_nhcthermostat allocate.h _mod_simplemixer _mod_numderivs2 _mod_coulomb _mod_fifo _mod_steepestdescent _mod_thermostat _mod_spin _mod_dispslaterkirkwood _mod_conjugategradient _mod_broydenmixer _mod_linkedlist _mod_berendsenthermostat _mod_thirdorder _mod_message _mod_ranlux _mod_commontypes _mod_mdintegrator _mod_tempprofile _mod_andersenthermostat _mod_lapackroutines _mod_simplealgebra _mod_mdcommon _mod_accuracy _mod_velocityverlet _mod_inputdata_ _mod_constants _mod_repcont _mod_sorting _mod_intrinsicprinter _mod_dispersion _mod_mixer _mod_periodic _mod_andersonmixer _mod_short_gamma _mod_scc_init _mod_dftbplsu
initprogram.o = initprogram.o $(_mod_geoopt) $(_mod_dispuff) $(_mod_diismixer) $(_mod_scc) $(_mod_dummythermostat) $(assert.h) $(_mod_slakocont) $(_mod_orbitalequiv) $(_mod_nhcthermostat) $(allocate.h) $(_mod_simplemixer) $(_mod_numderivs2) $(_mod_coulomb) $(_mod_fifo) $(_mod_steepestdescent) $(_mod_thermostat) $(_mod_spin) $(_mod_dispslaterkirkwood) $(_mod_conjugategradient) $(_mod_broydenmixer) $(_mod_linkedlist) $(_mod_berendsenthermostat) $(_mod_thirdorder) $(_mod_message) $(_mod_ranlux) $(_mod_commontypes) $(_mod_mdintegrator) $(_mod_tempprofile) $(_mod_andersenthermostat) $(_mod_lapackroutines) $(_mod_simplealgebra) $(_mod_mdcommon) $(_mod_accuracy) $(_mod_velocityverlet) $(_mod_inputdata_) $(_mod_constants) $(_mod_repcont) $(_mod_sorting) $(_mod_intrinsicprinter) $(_mod_dispersion) $(_mod_mixer) $(_mod_periodic) $(_mod_andersonmixer) $(_mod_short_gamma) $(_mod_scc_init) $(_mod_dftbplsu)
_mod_initprogram: initprogram.o
_mod_initprogram = $(initprogram.o)

inputdata_.o: inputdata_.F90 _mod_commontypes allocate.h _mod_message _mod_repcont _mod_dispersion _mod_slakocont _mod_linkedlist _mod_accuracy assert.h _mod_typegeometry
inputdata_.o = inputdata_.o $(_mod_commontypes) $(allocate.h) $(_mod_message) $(_mod_repcont) $(_mod_dispersion) $(_mod_slakocont) $(_mod_linkedlist) $(_mod_accuracy) $(assert.h) $(_mod_typegeometry)
_mod_inputdata_: inputdata_.o
_mod_inputdata_ = $(inputdata_.o)

mainio.o: mainio.F90 _mod_sparse2dense _mod_commontypes _mod_fileid allocate.h assert.h _mod_blasroutines _mod_fifo _mod_linkedlist _mod_charmanip _mod_periodic _mod_accuracy _mod_constants
mainio.o = mainio.o $(_mod_sparse2dense) $(_mod_commontypes) $(_mod_fileid) $(allocate.h) $(assert.h) $(_mod_blasroutines) $(_mod_fifo) $(_mod_linkedlist) $(_mod_charmanip) $(_mod_periodic) $(_mod_accuracy) $(_mod_constants)
_mod_mainio: mainio.o
_mod_mainio = $(mainio.o)

oldcompat.o: oldcompat.F90 _mod_xmlutils _mod_message _mod_hsdutils _mod_charmanip _mod_hsdutils2 _mod_flib_dom
oldcompat.o = oldcompat.o $(_mod_xmlutils) $(_mod_message) $(_mod_hsdutils) $(_mod_charmanip) $(_mod_hsdutils2) $(_mod_flib_dom)
_mod_oldcompat: oldcompat.o
_mod_oldcompat = $(oldcompat.o)

parser.o: parser.F90 _mod_charmanip _mod_dispuff _mod_stringlist _mod_hsdutils2 _mod_slakoeqgrid assert.h _mod_slakocont _mod_dispuffdata allocate.h _mod_lapackroutines _mod_hsdutils _mod_linkedlist _mod_dispslaterkirkwood _mod_flib_dom _mod_unitconversion _mod_generallist _mod_reppoly _mod_message _mod_hsdparser _mod_repcont _mod_oldcompat _mod_simplealgebra _mod_fileid _mod_wrappedpointers _mod_inputdata_ _mod_commontypes _mod_accuracy _mod_constants _mod_typegeometryhsd _mod_dispersion _mod_periodic _mod_oldskdata _mod_repspline
parser.o = parser.o $(_mod_charmanip) $(_mod_dispuff) $(_mod_stringlist) $(_mod_hsdutils2) $(_mod_slakoeqgrid) $(assert.h) $(_mod_slakocont) $(_mod_dispuffdata) $(allocate.h) $(_mod_lapackroutines) $(_mod_hsdutils) $(_mod_linkedlist) $(_mod_dispslaterkirkwood) $(_mod_flib_dom) $(_mod_unitconversion) $(_mod_generallist) $(_mod_reppoly) $(_mod_message) $(_mod_hsdparser) $(_mod_repcont) $(_mod_oldcompat) $(_mod_simplealgebra) $(_mod_fileid) $(_mod_wrappedpointers) $(_mod_inputdata_) $(_mod_commontypes) $(_mod_accuracy) $(_mod_constants) $(_mod_typegeometryhsd) $(_mod_dispersion) $(_mod_periodic) $(_mod_oldskdata) $(_mod_repspline)
_mod_parser: parser.o
_mod_parser = $(parser.o)

potentials.o: potentials.F90 _mod_accuracy _mod_commontypes assert.h allocate.h
potentials.o = potentials.o $(_mod_accuracy) $(_mod_commontypes) $(assert.h) $(allocate.h)
_mod_potentials: potentials.o
_mod_potentials = $(potentials.o)

